### ISSUE TITLE
Use a Rust-based hex float parser

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/wat#13]
Hex float parsing is [delegated to the C standard library right now](https://github.com/alexcrichton/wast/blob/66ceba22792b9e1f3aff46c65ca90062d6fa35cc/crates/parser/src/ast/token.rs#L237-L268) but this exposes us to platform differences (like [failing tests only on macOS](https://github.com/alexcrichton/wast/runs/261403418)). We should reimplement this in Rust. Crates like https://crates.io/crates/hexf-parse seem promising but don't work immediately. Needs more investigation.

**Comment by alexcrichton** [comment]
Right now we use `strtod` and `strtof`, which I thought wabt used as well, but turns out [they have their own hex float parser](https://github.com/WebAssembly/wabt/blob/f157909d791ea8f32248657062e8fdb3ed435eb5/src/literal.cc#L251-L406). Perhaps this can translate that!

**Comment by alexcrichton** [comment]
Looks like `strtod` and `strtof` are way off on MinGW as well, so yet another reason to use one canonical version instead of whatever the system happens to have.

**Comment by sunfishcode** [comment]
In case it helps, mozilla-central [has another one](https://dxr.mozilla.org/mozilla-central/source/js/src/wasm/WasmTextToBinary.cpp#2731).

**Comment by alexcrichton** [comment]
Thanks for the link @sunfishcode!

I was able to muster up enough energy and the was digestable enough this it ended up working!
